
CREATE TABLE CustomerCustomerDemo(
	CustomerID nchar (5) NOT NULL,
	CustomerTypeID nchar (10) NOT NULL,
	PRIMARY KEY (CustomerID, CustomerTypeID)
);
CREATE TABLE CustomerDemographics(
	CustomerTypeID nchar (10) NOT NULL,
	CustomerDesc CLOB NULL,
	PRIMARY KEY (CustomerTypeID)
);	
CREATE TABLE Region(
	RegionID int NOT NULL ,
	RegionDescription nchar (50) NOT NULL,
	PRIMARY KEY (RegionID, RegionDescription)
);
CREATE TABLE Territories(
	TerritoryID nvarchar2 (20) NOT NULL ,
	TerritoryDescription nchar (50) NOT NULL ,
    RegionID int NOT NULL,
	PRIMARY KEY (TerritoryID, TerritoryDescription, RegionID)
);
CREATE TABLE EmployeeTerritories(
	EmployeeID int NOT NULL,
	TerritoryID nvarchar2 (20) NOT NULL,
	PRIMARY KEY (EmployeeID, TerritoryID)
);
CREATE TABLE Employees (
	EmployeeID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	LastName nvarchar2 (20) NOT NULL ,
	FirstName nvarchar2 (10) NOT NULL ,
	Title nvarchar2 (30) NULL ,
	TitleOfCourtesy nvarchar2 (25) NULL ,
	BirthDate DATE NULL ,
	HireDate DATE NULL ,
	Address nvarchar2 (60) NULL ,
	City nvarchar2 (15) NULL ,
	Region nvarchar2 (15) NULL ,
	PostalCode nvarchar2 (10) NULL ,
	Country nvarchar2 (15) NULL ,
	HomePhone nvarchar2 (24) NULL ,
	Extension nvarchar2 (4) NULL ,
	Photo BLOB NULL ,
	Notes CLOB NULL ,
	ReportsTo INT NULL ,
	PhotoPath nvarchar2 (255) NULL ,
	CONSTRAINT "PK_Employees" PRIMARY KEY(EmployeeID),
	CONSTRAINT "FK_Employees_Employees" FOREIGN KEY(ReportsTo) REFERENCES Employees (EmployeeID)
);
CREATE TABLE Categories (
	CategoryID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	CategoryName nvarchar2 (15) NOT NULL ,
	Description CLOB NULL ,
	Picture BLOB NULL ,
	CONSTRAINT "PK_Categories" PRIMARY KEY(CategoryID)
);
CREATE TABLE Customers (
	CustomerID nchar (5) NOT NULL ,
	CompanyName nvarchar2 (40) NOT NULL ,
	ContactName nvarchar2 (30) NULL ,
	ContactTitle nvarchar2 (30) NULL ,
	Address nvarchar2 (60) NULL ,
	City nvarchar2 (15) NULL ,
	Region nvarchar2 (15) NULL ,
	PostalCode nvarchar2 (10) NULL ,
	Country nvarchar2 (15) NULL ,
	Phone nvarchar2 (24) NULL ,
	Fax nvarchar2 (24) NULL ,
	CONSTRAINT "PK_Customers" PRIMARY KEY(CustomerID)
);
CREATE TABLE Shippers (
	ShipperID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	CompanyName nvarchar2 (40) NOT NULL ,
	Phone nvarchar2 (24) NULL ,
	CONSTRAINT "PK_Shippers" PRIMARY KEY(ShipperID)
);
CREATE TABLE Suppliers (
	SupplierID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	CompanyName nvarchar2 (40) NOT NULL ,
	ContactName nvarchar2 (30) NULL ,
	ContactTitle nvarchar2 (30) NULL ,
	Address nvarchar2 (60) NULL ,
	City nvarchar2 (15) NULL ,
	Region nvarchar2 (15) NULL ,
	PostalCode nvarchar2 (10) NULL ,
	Country nvarchar2 (15) NULL ,
	Phone nvarchar2 (24) NULL ,
	Fax nvarchar2 (24) NULL ,
	HomePage CLOB NULL ,
	CONSTRAINT "PK_Suppliers" PRIMARY KEY(SupplierID)
);
CREATE TABLE Orders (
	OrderID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	CustomerID nchar (5) NULL ,
	EmployeeID INT NULL ,
	OrderDate DATE NULL ,
	RequiredDate DATE NULL ,
	ShippedDate DATE NULL ,
	ShipVia INT NULL ,
	Freight FLOAT DEFAULT (0) NULL,
	ShipName nvarchar2 (40) NULL ,
	ShipAddress nvarchar2 (60) NULL ,
	ShipCity nvarchar2 (15) NULL ,
	ShipRegion nvarchar2 (15) NULL ,
	ShipPostalCode nvarchar2 (10) NULL ,
	ShipCountry nvarchar2 (15) NULL ,
	CONSTRAINT "PK_Orders" PRIMARY KEY(OrderID),
	CONSTRAINT "FK_Orders_Customers" FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID),
	CONSTRAINT "FK_Orders_Employees" FOREIGN KEY(EmployeeID) REFERENCES Employees (EmployeeID),
	CONSTRAINT "FK_Orders_Shippers" FOREIGN KEY(ShipVia) REFERENCES Shippers (ShipperID)
);
CREATE TABLE Products (
	ProductID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	ProductName nvarchar2 (40) NOT NULL ,
	SupplierID INT NULL ,
	CategoryID INT NULL ,
	QuantityPerUnit nvarchar2 (20) NULL ,
	UnitPrice FLOAT  DEFAULT 0 NULL,
	UnitsInStock SMALLINT DEFAULT 0 NULL,
	UnitsOnOrder SMALLINT DEFAULT 0 NULL,
	ReorderLevel SMALLINT DEFAULT 0 NULL,
	Discontinued SMALLINT DEFAULT 0 NULL,
	CONSTRAINT "PK_Products" PRIMARY KEY(ProductID),
	CONSTRAINT "FK_Products_Categories" FOREIGN KEY (CategoryID) REFERENCES Categories (CategoryID),
	CONSTRAINT "FK_Products_Suppliers" FOREIGN KEY (SupplierID) REFERENCES Suppliers (SupplierID),
	CONSTRAINT "CK_Products_UnitPrice" CHECK (UnitPrice >= 0),
	CONSTRAINT "CK_ReorderLevel" CHECK (ReorderLevel >= 0),
	CONSTRAINT "CK_UnitsInStock" CHECK (UnitsInStock >= 0),
	CONSTRAINT "CK_UnitsOnOrder" CHECK (UnitsOnOrder >= 0)
);
CREATE TABLE OrderDetails (
	OrderID INT NOT NULL ,
	ProductID INT NOT NULL ,
	UnitPrice FLOAT DEFAULT 0 NOT NULL,
	Quantity SMALLINT DEFAULT 0 NOT NULL,
	Discount REAL DEFAULT 0 NOT NULL,
	CONSTRAINT "PK_Order_Details" PRIMARY KEY(OrderID,ProductID),
	CONSTRAINT "FK_Order_Details_Orders" FOREIGN KEY (OrderID) REFERENCES Orders (OrderID),
	CONSTRAINT "FK_Order_Details_Products" FOREIGN KEY (ProductID) REFERENCES Products (ProductID),
	CONSTRAINT "CK_Discount" CHECK (Discount >= 0 and (Discount <= 1)),
	CONSTRAINT "CK_Quantity" CHECK (Quantity > 0),
	CONSTRAINT "CK_UnitPrice" CHECK (UnitPrice >= 0)
);
